### ISSUE TITLE
New files for arab, dem, cop and gr are now available 

### ISSUE THREAD

**Issue by jcowey** [kadowa/papyri#10]
I finally got round to uploading the new arab, dem, cop and gr files. Would you, please, convert them and replace the old data in the database with the new data, when you have a few minutes at your disposal. 

https://github.com/kadowa/papyri/commit/eb75dbca4a25f84a8e8f2b53aee08b4486b3cdaa
https://github.com/kadowa/papyri/commit/fdd9453b1ad8bacbebd822f6a0f45acc08dfec85
https://github.com/kadowa/papyri/commit/8a2162d5aeed72ef87f582480cd95c8fb628ccc3
https://github.com/kadowa/papyri/commit/89331b6b4c950665552cc022598d4711696c5b52

Many thanks and sorry once again for the mess up on my part.

**Comment by kadowa** [comment]
Ich bekomme leider beim Import der neuen Dateien Probleme mit dem Encoding. Das letzte Mal waren die Dateien UTF-8. Wenn ich auf ISO 8859-1 umstelle, bekomme ich den Import zwar fehlerfrei hin, aber die griechischen und arabischen Zeichen werden noch unkenntlicher als bisher. Kann man in Filemaker beim Export das Encloding auswählen?

**Comment by kadowa** [comment]
Außerdem bekomme ich noch einen Fehler, der die Anzahl der Spalten bei _gr_ betrifft. Kann es sein, dass hier nicht alle Spalten exportiert wurden?

**Comment by kadowa** [comment]
https://github.com/kadowa/papyri/commit/2c2573aede3ffb0a08e752b35b45c369f145683d
