### ISSUE TITLE
Recto and verso in separate table

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#11]
I am currently exploring the possibility of separating the data into two tables, one for the (physical) papyri, and one for descriptions of their pages (*recto* and *verso* – there is no hidden third option, is there? :wink:) which is referenced by the first.

The best chance to do this automatized seems to me to rely on the information in the ```rv``` and ```andere_seite``` field. If I understand correctly, ```rv``` specifies, wether a record describes *recto*, *verso*, or both and ```andere_seite``` indicates, if there is a separate record for the other page or if this page is empty.

Here is a survey of all distinct combinations of ```rv``` and ```andere_seite``` combined with their count in the current database:

```
# COUNT(*), rv, andere_seite
793, , 
5, Fleischseite, Verso frei
3, Fleischseite, s. eigenen Datensatz
1, Fleischseite, Haarseite frei
1, Fleischseite, Schriftspuren
2, Fleischseite vermutlich, Haarseite frei vermutlich
3, Haarseite, s. eigenen Datensatz
2, Haarseite u. Fleischseite, s. eigenen Datensatz
1, Haarseite u. Fleischseite,               
4866, Recto, Verso frei
3931, Recto, s. eigenen Datensatz
376, Recto, Schriftspuren
351, Recto, Tintenspuren
205, Recto, 
31, Recto, Verso frei vermutlich
8, Recto,               
6, Recto, Tintenspuren(?)
3, Recto, Schriftspuren(?)
2, Recto, ?
1, Recto,  Tintenspuren             
1, Recto, Recto frei
1, Recto, s. P. Heid. Inv. G 315
1, Recto, Zeichnung u. Schriftspuren
1, Recto, S. P. Heid. Inv. G(Dem) 742c
1, Recto, Unbekannt
356, Recto u. Verso, 
327, Recto u. Verso,               
27, Recto u. Verso, s. eigenen Datensatz
6, Recto u. Verso, Verso frei
1, Recto u. Verso, Tintenspuren
1, Unbekannt, 
3891, Verso, s. eigenen Datensatz
50, Verso, 
13, Verso, Recto frei
8, Verso, Verso frei
3, Verso, Tintenspuren
2, Verso, Schriftspuren
2, Verso, s. P. Heid. Inv. G 295
2, Verso,               
1, Verso, s. P. Heid. Inv. Dem. 742c
1, Verso, Siehe G 4737 Recto
1, Verso, Siehe G 4745 Recto
```

My observations so far (@jcowey, feel free to add your thoughts):

 * 793 records don't have any information on pages. Is there a default state we can assume for those?
 * How can *Haarseite* and *Fleischseite* be matched to *recto* and *verso* (I took the liberty of converting *Rückseite* to *verso* and *Vorderseite* to *recto* already)? I suggest storing this information in a separate column and convert the terms to *recto* and *verso* for ease of processing.
 * A few ```andere_seite``` fields contain actual references to the record describing the page, but most have to be matched via the ```p_heid_inv``` etc., so I suggest we ignore this info.
 * Some of the combinations don't make sense, in particular
   *  ```Recto u. Verso, s. eigenen Datensatz```
   *  ```Recto, Recto frei```
   *  ```Verso, Verso frei```

I will follow up with a list of ids affected by the last point; they probably require manual correction.

**Comment by kadowa** [comment]
```
SELECT id, rv, andere_seite FROM papyri.papyri WHERE rv="Recto u. Verso" AND andere_seite="s. eigenen Datensatz";
```

```
# id, rv, andere_seite
80, Recto u. Verso, s. eigenen Datensatz
106, Recto u. Verso, s. eigenen Datensatz
190, Recto u. Verso, s. eigenen Datensatz
279, Recto u. Verso, s. eigenen Datensatz
1035, Recto u. Verso, s. eigenen Datensatz
1078, Recto u. Verso, s. eigenen Datensatz
8440, Recto u. Verso, s. eigenen Datensatz
8655, Recto u. Verso, s. eigenen Datensatz
8766, Recto u. Verso, s. eigenen Datensatz
10802, Recto u. Verso, s. eigenen Datensatz
11359, Recto u. Verso, s. eigenen Datensatz
11393, Recto u. Verso, s. eigenen Datensatz
11429, Recto u. Verso, s. eigenen Datensatz
11585, Recto u. Verso, s. eigenen Datensatz
11878, Recto u. Verso, s. eigenen Datensatz
12143, Recto u. Verso, s. eigenen Datensatz
12750, Recto u. Verso, s. eigenen Datensatz
12779, Recto u. Verso, s. eigenen Datensatz
12967, Recto u. Verso, s. eigenen Datensatz
13113, Recto u. Verso, s. eigenen Datensatz
15035, Recto u. Verso, s. eigenen Datensatz
15042, Recto u. Verso, s. eigenen Datensatz
15638, Recto u. Verso, s. eigenen Datensatz
17215, Recto u. Verso, s. eigenen Datensatz
17220, Recto u. Verso, s. eigenen Datensatz
17467, Recto u. Verso, s. eigenen Datensatz
```

**Comment by kadowa** [comment]
```
SELECT id, rv, andere_seite FROM papyri.papyri WHERE rv="Recto" AND andere_seite="Recto frei";
```

```
# id, rv, andere_seite
10392, Recto, Recto frei
```

**Comment by kadowa** [comment]
```
SELECT id FROM papyri.papyri WHERE rv="Verso" AND andere_seite="Verso frei";
```

```
# id
10254
11848
14874
14991
17355
```

**Comment by kadowa** [comment]
```
SELECT id FROM papyri.papyri WHERE rv="Unbekannt";
```

```
# id
191
```

**Comment by jcowey** [comment]
@kadowa 
Can this issue now be closed. I think that everything here has been solved by issues:

https://github.com/kadowa/papyri/issues/15
https://github.com/kadowa/papyri/issues/16
https://github.com/kadowa/papyri/issues/17
https://github.com/kadowa/papyri/issues/18

**Comment by kadowa** [comment]
Almost; we also need unique identifiers to do this, so #9 needs to be closed as well.

**Comment by kadowa** [comment]
#14 as well, of course.

**Comment by jcowey** [comment]
Ah OK!

**Comment by kadowa** [comment]
TO DO:

- [ ] new field for standardized front/back info
- [ ] create separate tables ('papyri` and `pages`)
- [ ] fill tables
- [ ] link between tables (new fields `front` and `back` in `papyri`)
- [ ] add new fields
- [ ] adapt `tables.py` to new db structure
- [ ] integrate `rv`, `andere_seite`?

**Comment by kadowa** [comment]
Procedure for linking back and front page from papyrus table:

- [ ] clean (or store and clean later) ids which appear more than two times in the pages table
  ```
# project_id, COUNT(project_id)
p_aram_2, 3
p_g_216, 3
p_g_295, 3
p_g_310, 4
p_g_8, 3
p_g_81, 3
p_hebr_1, 4
p_hebr_10, 3
p_hebr_11, 3
p_hebr_13, 3
p_hebr_14, 3
p_hebr_16, 3
p_hebr_2, 3
p_hebr_21, 3
p_hebr_23, 4
p_hebr_26, 3
p_hebr_27, 3
p_hebr_28, 3
p_hebr_29, 3
p_hebr_30, 3
p_hebr_31, 3
p_hebr_32, 3
p_hebr_33, 3
p_hebr_4, 3
p_hebr_5, 3
p_hebr_6, 3
p_hebr_7, 3
p_hebr_8, 3
  ```
- [ ] papyri, which have one page marked `fb` and one marked `f`or `b`: convert `fb` to opposite page (and store id for possible future corrections?)
- [ ] papyri, which have exactly one page marked `fb`: duplicate page, mark original as `f` and duplicate as `b`

**Comment by jcowey** [comment]
@kadowa Lajos Berkes and I were due to have another session after coffee and before lunch today on #31. Is that going to get in your way?

**Comment by kadowa** [comment]
Not at all; I am currently working with a throwaway copy of the database since I can't run the scripts finally until we have unique ids. So I should be the one getting out of the way. ;-)
