### ISSUE TITLE
Storage of images 

### ISSUE THREAD

**Issue by jcowey** [kadowa/papyri#12]
At present there are images of papyri / ostraca etc stored at:
- 600 dpi tiff
- 150 dpi jpg
- 72 dpi jpg
  These are stored on DVDs or elsewhere.
  In the future images should be stored on a server in the UB. That being the only place that they are stored (to avoid becoming out of sync). Access to them should be guaranteed to accredited users in the Institut für Papyrologie. 
  How they are made available to the public at large should be controlled through the database. 
- Published papyri / ostraca / etc should be accompanied by full size tiffs. 
- Unpublished papyri / ostraca / etc should only be made available as thumbnails.

Resultant questions:
- What do we store on the server? Just 600 dpi tiffs? or are the 72 jpgs also necessary?
  - only 600 dpi tiffs are necessary
- Do we want to make the images available at 600, 150 and 72?
- How large is the total MB size of all images?

https://docs.google.com/spreadsheets/d/1OMw6NLkmJHphReUZyRvMrdMnsejCYoNJsC-La3oS1J4/edit#gid=0

**Comment by kadowa** [comment]
I think we answered those questions in our last meetings; I'm including the answers her for the sake of completeness:

- We store the highest available resolution, smaller versions can be calculated, if necessary.
- Total size of images for each language:

```
74G	arab
497M	aram
29G	cop
13G	dem
82G	gr
1,7G	hebr
661M	hier
650M	lat
51M	pah
7,9M	syr
```

**Comment by kadowa** [comment]
@jcowey, can this issue be closed?
