### ISSUE TITLE
Separate table fields

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#14]
Separate table fields into _Papyrus_, _Seite_ or both (if unclear) in **NeueKatalogFelder**.

**Comment by kadowa** [comment]
I had a look at the Google doc and the info which fields go into which table is still incomplete. If you are in doubt, just include the column in both tables per default. We can always throw them out later.

**Comment by jcowey** [comment]
Put a "x" in the column Papyrus, if the content of the field only refers to the papyrus (the object). A "x" goes in into the column Seite if the content refers only to what is on the "recto" or what is on the "verso". In cases of doubt an "x" goes into both columns

**Comment by kadowa** [comment]
I just had a look at NeueKatalogFelder – so far I can't derive any separation of fields (there is an "x" for every field in the column Papyrus except for one). Do you think it makes any sense at all to attempt a clear separation, @jcowey? If you think it's simply not possible, because the data is too heterogeneous, we need to come up with a new plan quickly.

**Comment by jcowey** [comment]
@kadowa, please now look at NeueKatalogFelder.
If you choose Sortiert nach Feldnamen sheet you should have all the information you need.
Only the two fields `eingeben_am` and `zuletzt_geaendert_am` have a cross in both Papyrus and Seite. I think that that does make sense.
You will find that I have added at the bottom the list of new fields. These new fields are also to be found in the alphabetic list. Do what is necessary for you with this sheet, make changes where you need them for your scripts.

**Comment by jcowey** [comment]
@kadowa is everything now in order so that you can now continue with the process of restructuring the database?

**Comment by kadowa** [comment]
Looks good!
