### ISSUE TITLE
Unclear page assignment: rv=Recto, andere_seite=Recto frei

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#15]
```
SELECT id FROM papyri.papyri WHERE rv="Recto" AND andere_seite="Recto frei";
```

```
# id
10392
```

**Comment by jcowey** [comment]
andere_seite="Recto frei" is now
andere_seite="s. eigenen Datensatz"
by the way all the entries "None" disappeared when I hit submit.

**Comment by jcowey** [comment]
Can you now please test and let us know whether this issue is now closed. I would say it can now be closed.

**Comment by kadowa** [comment]
Looks good!
