### ISSUE TITLE
Unclear page assignment: rv="Unbekannt"

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#17]
```
SELECT id FROM papyri.papyri WHERE rv="Unbekannt";
```

```
# id
191
```

**Comment by jcowey** [comment]
The original is lost! We will have to check: Grohmann, Arabic Papyri in the Egyptian Library, Vol. V, p. 93.

**Comment by jcowey** [comment]
For the sake of database compliance we decided to give "rv" the value "Recto". If this proves wrong it can be corrected in the future.

**Comment by jcowey** [comment]
This should now be fine.
