### ISSUE TITLE
Unclear page assignment: rv=Recto u. Verso", andere_seite="s. eigenen Datensatz

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#18]
```
SELECT id FROM papyri.papyri WHERE rv="Recto u. Verso" AND andere_seite="s. eigenen Datensatz";
```

```
# id
```
- [x] `80`
- [x] `106`
- [x] `190`
- [x] `279`
- [x] `1035`
- [x] `1078`
- [x] `8440`
- [x] `8655`
- [x] `8766`
- [x] `10802`
- [x] `11359`
- [x] `11393`
- [x] `11429`
- [x] `11585`
- [x] `11878`
- [x] `12143`
- [x] `12750`
- [x] `12779`
- [x] `12967`
- [x] `13113`
- [x] `15035`
- [x] `15042`
- [x] `15638`
- [x] `17215`
- [x] `17220`
- [x] `17467`

**Comment by jcowey** [comment]
8440 = Koptisch 174; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
8655 = Koptisch 313; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
8766 = Koptisch 386; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
10802 = Demotisch 724; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
11359 = G 66; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
Can you please confirm the following? By removing "s. eigenen Datensatz" from the field andere_seite and leaving the entry "Recto u. Verso" in the field rv, we are leaving a situation that can be dealt with as far as database structure is concerned. This assumption is, I hope, correct.

**Comment by kadowa** [comment]
Yes – the other option would be (if there is indeed an "eigene Datensatz" for `andere_seite`) to change "Recto u. Verso" to "Recto" or "Verso", depending on which it actually refers to.

**Comment by jcowey** [comment]
11393 = G 90; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
11429 = G 122; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records. "Verschollen"

**Comment by jcowey** [comment]
11585 = G 239a; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.
G 239 is complex and should be reworked in future

**Comment by jcowey** [comment]
12143 = G 681a; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
12750 = G 1193; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
12779 = G 1215; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
12967 = G 1364; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
13113 = G 1490; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
15035 = G 3082; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
15042 = G 3088; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
15638 = G 3607; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
17215 = G 4926; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records. Not really.

**Comment by jcowey** [comment]
17220 = G 4930; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
17467 = G 4930; only one record in the database. There should be two records: one for the recto and another one for the verso. We have removed "s. eigenen Datensatz" for the present. This record may still have to be broken into TWO separate records.

**Comment by jcowey** [comment]
This should now be finished! :)
