### ISSUE TITLE
Image matching

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#20]
Number of images in folders, number of records in database:

```
arab, 6008, 5045
aram, 4, 4
cop, 2490, 1993
dem, 691, 705
gr, 7255, 6578
hebr, 56, 61
hier, 46, 34
lat, 17, 18
ostr, na, 759
pah, 2, 84
syr, 2, 7
```

**Comment by kadowa** [comment]
@jcowey, in the folder containing the Greek images, most file names start with a `G` (for Greek, I assume), but there is also a small number of file names starting with `SEP`. For example, there are `G0026R.tif` and `SEP26A.tif`. I assume that the digits in the file name refer to `p_heid_inv_nr`, so do those files concern the same papyrus or are the `SEP` files something completely different? Also, they all contain an `A`or a `B`, but no `R`and `V`.

**Comment by jcowey** [comment]
I shall get Elke to have a look at this. I had next to nothing to do with photography etc.

**Comment by kadowa** [comment]
Any news on this issue?

**Comment by jcowey** [comment]
http://heidi.ub.uni-heidelberg.de/papyri/default/table?keywords=papyri.id+%3D+%2212049%22
(P.Heid. Inv. G 600)
maps as one to many onto all of the sep images. 26A is the 26 A folio side of the codex.

**Comment by jcowey** [comment]
@kadowa 
hope that the above makes the Sachverhalt clear.

**Comment by kadowa** [comment]
Thanks, it does. So this is a special case where 29 papyri pages have been grouped into one record – but is this the only codex in the database or are there more and we just haven't talked about this phenomenon yet? Because this will be very hard to model according to #11.

**Comment by jcowey** [comment]
There are probably a few more examples. I would think maybe 5 or a few more. New records could be created in the database.

**Comment by kadowa** [comment]
Ok, this seems like a manageable number. Can you get me a list? Separate records might be the easiest ways to solve this, but you will probably want to keep information about the codex. We might need a third table after all or at least a new field to model this.

**Comment by kadowa** [comment]
I created a new issue for discussing codices: #22
