### ISSUE TITLE
o_heid_inv and p_heid_inv

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#21]
Here is the result of the query

`SELECT o_heid_inv, p_heid_inv, COUNT(*) FROM papyri.papyri GROUP BY o_heid_inv, p_heid_inv;`

```
# o_heid_inv, p_heid_inv, COUNT(*)
NULL, NULL, '48'
NULL, 'ÄgInst', '4'
NULL, 'Arab.', '4981'
NULL, 'Aram.', '2'
NULL, 'Aram. (arab)', '3'
NULL, 'Dem', '5'
NULL, 'Dem.', '677'
NULL, 'Dem. (Hier.)', '4'
NULL, 'G', '6554'
NULL, 'Hebr', '1'
NULL, 'Hebr.', '53'
NULL, 'Hebr. (arab)', '19'
NULL, 'Hier.', '32'
NULL, 'Hier. (Dem.)', '2'
NULL, 'Kopt.', '1969'
NULL, 'Lat.', '15'
NULL, 'Lat. (G)', '3'
NULL, 'Pahl.', '84'
NULL, 'Syr.', '7'
'', 'Arab.', '20'
'', 'Aram.', '1'
'', 'Dem.', '13'
'', 'G', '24'
'', 'Hebr.', '14'
'', 'Kopt.', '21'
'dem', NULL, '65'
'dem - G', NULL, '1'
'G', NULL, '592'
'G (?)', NULL, '8'
'G Kopt (?)', NULL, '1'
'G, dem', NULL, '3'
'G, dem (?)', NULL, '2'
'G, dem.', NULL, '2'
'hier', NULL, '4'
'Kopt', NULL, '30'
'Kopt (?)', NULL, '2'
'Kopt.', NULL, '2'
```

Since they are perfectly distinct, it would be possible to merge `o_heid_inv` and `p_heid_inv` into one field – if that is advisable?

**Comment by kadowa** [comment]
It might make sense to get rid of the `(?)`s (I don't think they should be part of an inventory number) and standardize `'G, dem'` and `'G, dem.'` and similar spelling variants.

**Comment by kadowa** [comment]
Also, there seem to be 48 rogue records without any inventory number (see the first line of the result).

**Comment by jcowey** [comment]
@kadowa how can I find these rogue records? I tried
papyri.o_heid_inv contains "None"
papyri.o_heid_inv starts with "Non"
and get no returns

**Comment by kadowa** [comment]
Unfortunately, the web2py default search form seems to be unable to handle `NULL` values. I used this SQL on the database:
```
SELECT id, p_heid_inv_nr FROM papyri.papyri WHERE o_heid_inv IS NULL AND p_heid_inv IS NULL;
```

```
# id, p_heid_inv_nr
'9297', '744'
'19908', '298'
'19934', '324'
'19975', '365'
'20073', '463'
'20084', '474'
'20087', '477'
'20091', '481'
'20097', '487'
'20098', '488'
'20099', '489'
'20100', '490'
'20102', '492'
'20103', '493'
'20104', '494'
'20107', '497'
'20108', '498'
'20118', '508'
'20119', '509'
'20121', '511'
'20123', '513'
'20125', '515'
'20127', '517'
'20158', '548'
'20159', '549'
'20163', '553'
'20164', '554'
'20179', '569'
'20184', '574'
'20188', '578'
'20194', '584'
'20198', '588'
'20199', '589'
'20200', '590'
'20206', '596'
'20207', '597'
'20208', '598'
'20216', '606'
'20219', '609'
'20225', '615'
'20226', '616'
'20227', '617'
'20228', '618'
'20229', '619'
'20242', '632'
'20243', '633'
'20348', '718'
'20353', '723'
```

**Comment by kadowa** [comment]
So can we move all entries in `o_heid_inv` into `p_heid_inv`?

**Comment by jcowey** [comment]
@kadowa just created #23 in order to describe the steps necessary in order to get rid of the field `o_heid_inv`.

**Comment by kadowa** [comment]
Created #27 to deal with the remaining question of the rogue records.

**Comment by kadowa** [comment]
Reminder: We need to consider `material` when generating unique project ids – otherwise we end up with non-unique identifiers again. /cc #9
