### ISSUE TITLE
Treatment of o_heid_inv

### ISSUE THREAD

**Issue by jcowey** [kadowa/papyri#23]
Steps:
Please make sure that when `o_heid_inv` has a value that `material` has the value "Ostrakon". 

- [x] If `material` does not have the value "Ostrakon", please add the value "Ostrakon" to `material`.

- [x] Now transfer the value of `o_heid_inv` to `p_heid_inv` AND `sprache`

- [x] Now delete the field `o_heid_inv`

**Comment by kadowa** [comment]
Will do!

**Comment by kadowa** [comment]
There is one record that has `material` `Holztafel`instead of `Ostrakon`:

```
# id, o_heid_inv, material
'20357', 'dem - G', 'Holztafel'
```

Change that to `Ostrakon` or keep because an Ostrakon is a Holztafel?

**Comment by jcowey** [comment]
OK for the moment. Not perfect as a solution but I can live with it for the moment and we have a record of the change here.

**Comment by kadowa** [comment]
Actually, I don't think I should transfer `o_heid_inv` directly to `sprache` – the former uses abbreviations, the latter the whole language. I suggest using the following mapping:

```
# o_heid_inv -> sprache
'G' -> 'Griechisch'
'G, dem' -> 'Griechisch, Demotisch'
'G, dem.' -> 'Griechisch, Demotisch'
'Kopt.' -> 'Koptisch'
'G (?)' -> 'Griechisch (?)'
'Kopt' -> 'Koptisch'
'dem' -> 'Demotisch'
'Kopt (?)' -> 'Koptisch (?)'
'G Kopt (?)' ->  'Griechisch, Koptisch (?)'
'G, dem (?) ' ->  'Griechisch, Demotisch (?)'
'hier' -> 'Hieratisch'
'dem - G' -> 'Griechisch, Demotisch'
```

Ok?

**Comment by jcowey** [comment]
Absolutely. Many thanks. Great. Database improvement :)

**Comment by kadowa** [comment]
In the wake of this I just opened another issue concerning the `sprache` field specifically, see #25.
