### ISSUE TITLE
Standardize field 'sprache'

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#25]
I suggest turning the field `sprache` into an actual list (currently it's a string) to standardize the values. Currently these are the distinct values in the database:

```
'Arabisch'
'Arabisch, Griechisch'
'Arabisch möglicherweise'
'Griechisch'
'Arabisch?'
'Schriftspuren, sehr eventuell arabisch'
'Koptisch, Arabisch'
'Arabisch [?]'
'Leer'
'Arabisch, Koptisch'
'Arabisch oder Pseudo-Arabisch'
'Arabisch und Griechisch\n'
'Arabisch- Griechisch'
'Arabisch-Griechisch'
'Arabisch vermutlich'
'Griechisch, arabisch'
'Arabisch- Griechich'
'Arabisch (Jüdisch-Arabisch)'
'Arabisch - Griechisch'
'Arabisch (Christlich-Arabisch)'
'Arabisch (Christlich-Arabisch), Koptisch'
'Koptisch, Arabisch (Christlich-Arabisch)'
'Arabisch und Griechisch'
'Arabisch, Arabisch (Jüdisch-Arabisch)'
'Arabisch- Griechisch ?'
'Hebräisch'
'Koptisch'
'Griechisch(?)'
'Griechisch/Koptisch/Arabisch'
'Griechisch/Arabisch'
'Griechisch/Koptisch'
'Koptisch/Griechisch'
'?'
'Lateinisch'
'Koptisch/Griechisch\n'
'Koptisch/Arabisch(?)'
'Koptisch/Griechisch(?)'
'Koptisch/Arabisch'
'Arabisch/Koptisch/Griechisch'
'Koptisch/Arabisch\n'
'Koptisch/Arabisch/Griechisch'
'Koptisch?'
'Griechisch(?)\n'
'Demotisch'
'Demotisch/Griechisch'
'Demotisch/Griechisch(?)'
'Griechisch/Lateinisch'
'Griechisch / Koptisch'
'Lateinisch(?)'
'Griechisch - Koptisch'
'Griechisch/Demotisch'
'Koptisch - Griechisch'
'(?)'
'Demotisch (?)'
'Koptisch (?)'
'Koptisch(?)'
'Griechisch?'
'Griechisch\n'
'Arabisch(?)'
'Lateinisch/Griechisch'
'Griechisch/Syrisch'
```

To model the `(?)`/`möglicherweise` I suggest adding an additional field, `sprache_unsicher` or similar. `Schriftspuren, sehr eventuell arabisch` is the only value we won't be able to reproduce completely using this modeling.

**Comment by jcowey** [comment]
See the table in:
https://docs.google.com/spreadsheets/d/1TjhyqLVLjf6SJgl8H1YzGAYMOWr0NvJaaLYPATWfWtE/edit#gid=0

**Comment by kadowa** [comment]
Just to get this right: Does the order of the languages actually matter? Because both `Arabisch - Koptisch` and `Arabisch - Koptisch` appear among the new values. If not, I could just make this field an actual list, as proposed.

**Comment by jcowey** [comment]
The order is important!! (tends to indicate that there is distinctly more Arabic than Coptic or vice versa).
Yes just use the list in the google spreadsheet as a list of change and replace functions.

**Comment by jcowey** [comment]
and add a new database field sprache_unsicher as you yourself suggested

**Comment by kadowa** [comment]
Thanks for clearing that up. I will stick to your table then. :smile:

**Comment by kadowa** [comment]
Sorry, need to reopen this. There are 24 records, where `sprache` is empty. In this case, should I derive the value from `p_heid_inv`?

```
# id, sprache, p_heid_inv
'91', '', 'Arab.'
'191', '', 'Arab.'
'1035', '', 'Arab.'
'1078', '', 'Arab.'
'2319', '', 'Arab.'
'3448', '', 'Arab.'
'3449', '', 'Arab.'
'3584', '', 'Arab.'
'3585', '', 'Arab.'
'4230', '', 'Arab.'
'4231', '', 'Arab.'
'4974', '', 'Arab.'
'4977', '', 'Aram.'
'5022', '', 'Arab.'
'5023', '', 'Arab.'
'8381', '', 'Kopt.'
'8382', '', 'Kopt.'
'8655', '', 'Kopt.'
'11909', '', 'G'
'12000', '', 'G'
'12179', '', 'G'
'12597', '', 'G'
'14421', '', 'G'
'15998', '', 'G'
```
