### ISSUE TITLE
Standardize field 'p_heid_inv'

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#26]
After completing #23, there will be mixed values for `p_heid_inv`:

```
Arab.
Aram.
Hebr.
Hebr
Aram. (arab)
Kopt.
Kopt
Kopt (?)
G
G, dem
G, dem (?)
G, dem.
G (?)
G Kopt (?)
Dem.
Dem
Dem. (Hier.)
dem
dem - G
ÄgInst
Hebr. (arab)
Hier.
Hier. (Dem.)
hier
Lat.
Lat. (G)
Pahl.
Syr.
```
If possible, standardize?

**Comment by jcowey** [comment]
Would you, please implement the following changes:
 - [ ] Hebr => Hebr.
 - [ ] Kopt => Kopt.
 - [ ] dem => Dem.
 - [ ] Dem => Dem.
 - [ ] hier => Hier.
 - [ ] arab = Arab.
getting rid of trailing space (if that makes a difference in the DB).
Would you then please create a new list of unique values for the field.

**Comment by kadowa** [comment]
What about the brackets and question marks? As these values make up part of our final identifiers, I strongly vote for getting rid of them. Isn't the uncertainty and possible combination of two languages encoded in `sprache` already?

**Comment by jcowey** [comment]
Please get rid of all question marks. You are quite right. The information is stored in `sprache`

**Comment by kadowa** [comment]
Updated list of unique values, with suggestions for further cleaning-up operations:

```
# p_heid_inv
'Arab.'
'Aram.'
'Hebr.'
'Aram. (arab)' -> 'Aram.'
'Kopt.'
NULL
'G'
'Dem.'
'Dem. (Hier.)' -> 'Dem.'
'ÄgInst'
'Hebr. (arab)' -> 'Hebr.'
'Hier.'
'Hier. (Dem.)' -> 'Hier.'
'Lat.'
'Lat. (G)' -> 'Lat.'
'G, dem' -> 'G'
'G, dem.' -> 'G'
'G Kopt (?)' -> 'G'
'G, dem (?)' -> 'G'
'dem - G' -> 'Dem.'
'Pahl.'
'Syr.'
```

**Comment by kadowa** [comment]
Current list of distinct values and their count in `p_heid_inv`:

```
# p_heid_inv, COUNT(p_heid_inv)
ÄgInst., 4
Arab., 5001
Aram., 6
Dem., 765
G., 7186
Hebr., 87
Hier., 38
Kopt., 2024
Lat., 18
Pahl., 84
Syr., 7
```
