### ISSUE TITLE
Records without 'p_heid_inv'

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#27]
The following records have no value in 'p_heid_inv'. For all but one, `sprache`is empty as well, so it might be difficult to derive the correct  'p_heid_inv'.

```
# id, p_heid_inv_nr, p_heid_inv, sprache
'9297', '744', NULL, 'Koptisch'
'19908', '298', NULL, ''
'19934', '324', NULL, ''
'19975', '365', NULL, ''
'20073', '463', NULL, ''
'20084', '474', NULL, ''
'20087', '477', NULL, ''
'20091', '481', NULL, ''
'20097', '487', NULL, ''
'20098', '488', NULL, ''
'20099', '489', NULL, ''
'20100', '490', NULL, ''
'20102', '492', NULL, ''
'20103', '493', NULL, ''
'20104', '494', NULL, ''
'20107', '497', NULL, ''
'20108', '498', NULL, ''
'20118', '508', NULL, ''
'20119', '509', NULL, ''
'20121', '511', NULL, ''
'20123', '513', NULL, ''
'20125', '515', NULL, ''
'20127', '517', NULL, ''
'20158', '548', NULL, ''
'20159', '549', NULL, ''
'20163', '553', NULL, ''
'20164', '554', NULL, ''
'20179', '569', NULL, ''
'20184', '574', NULL, ''
'20188', '578', NULL, ''
'20194', '584', NULL, ''
'20198', '588', NULL, ''
'20199', '589', NULL, ''
'20200', '590', NULL, ''
'20206', '596', NULL, ''
'20207', '597', NULL, ''
'20208', '598', NULL, ''
'20216', '606', NULL, ''
'20219', '609', NULL, ''
'20225', '615', NULL, ''
'20226', '616', NULL, ''
'20227', '617', NULL, ''
'20228', '618', NULL, ''
'20229', '619', NULL, ''
'20242', '632', NULL, ''
'20243', '633', NULL, ''
'20348', '718', NULL, ''
'20353', '723', NULL, ''
```

**Comment by jcowey** [comment]
@kadowa 
Do we already have a controlled / authority list of values from `p_heid_inv`? If we do, would you please append a comment in this issue with the list.
'9297', '744', 'Koptisch' seems odd. It should, I think be, '9297', '744', 'Kopt.'

**Comment by kadowa** [comment]
I added such a list here: https://github.com/kadowa/papyri/issues/26#issuecomment-232059052

**Comment by kadowa** [comment]
Regarding your other question: I made an error copying and pasting the list; 'Koptisch' is the value of `sprache` for this record, `p_heid_inv` is NULL. It's the case I mentioned above, where `p_heid_inv` could be derived from `sprache`.

**Comment by jcowey** [comment]
List
 - [x] '9297', '744', NULL, 'Koptisch'
 - [ ] '19908', '298', NULL, ''
 - [ ] '19934', '324', NULL, ''
 - [ ] '19975', '365', NULL, ''
 - [ ] '20073', '463', NULL, ''
 - [ ] '20084', '474', NULL, ''
 - [ ] '20087', '477', NULL, ''
 - [ ] '20091', '481', NULL, ''
 - [ ] '20097', '487', NULL, ''
 - [ ] '20098', '488', NULL, ''
 - [ ] '20099', '489', NULL, ''
 - [ ] '20100', '490', NULL, ''
 - [ ] '20102', '492', NULL, ''
 - [ ] '20103', '493', NULL, ''
 - [ ] '20104', '494', NULL, ''
 - [ ] '20107', '497', NULL, ''
 - [ ] '20108', '498', NULL, ''
 - [ ] '20118', '508', NULL, ''
 - [ ] '20119', '509', NULL, ''
 - [ ] '20121', '511', NULL, ''
 - [ ] '20123', '513', NULL, ''
 - [ ] '20125', '515', NULL, ''
 - [ ] '20127', '517', NULL, ''
 - [ ] '20158', '548', NULL, ''
 - [ ] '20159', '549', NULL, ''
 - [ ] '20163', '553', NULL, ''
 - [ ] '20164', '554', NULL, ''
 - [ ] '20179', '569', NULL, ''
 - [ ] '20184', '574', NULL, ''
 - [ ] '20188', '578', NULL, ''
 - [ ] '20194', '584', NULL, ''
 - [ ] '20198', '588', NULL, ''
 - [ ] '20199', '589', NULL, ''
 - [ ] '20200', '590', NULL, ''
 - [ ] '20206', '596', NULL, ''
 - [ ] '20207', '597', NULL, ''
 - [ ] '20208', '598', NULL, ''
 - [ ] '20216', '606', NULL, ''
 - [ ] '20219', '609', NULL, ''
 - [ ] '20225', '615', NULL, ''
 - [ ] '20226', '616', NULL, ''
 - [ ] '20227', '617', NULL, ''
 - [ ] '20228', '618', NULL, ''
 - [ ] '20229', '619', NULL, ''
 - [ ] '20242', '632', NULL, ''
 - [ ] '20243', '633', NULL, ''
 - [ ] '20348', '718', NULL, ''
 - [ ] '20353', '723', NULL, ''

**Comment by jcowey** [comment]
In the above list, I am entering "Unbeschriftet" in `Bemerkungen`; "keine" in `Sprache` and leaving `p_heid_inv` empty

**Comment by jcowey** [comment]
@kadowa should now be finished. Would you please check and confirm.
