### ISSUE TITLE
Cleaning p_heid_inv

### ISSUE THREAD

**Issue by jcowey** [kadowa/papyri#31]
Took this out of #9 to ease dealing with it for me.

Final question on this issue (hopefully). After studying `p_heid_inv_erg` in more detail I am convinced it should not become part of the inventory number – in almost all cases, it seems to be information on related papyri or fragments and often contains free text. I made another list of unique identifiers *without* `p_heid_inv_erg` and it looks pretty good. There are only a few that are not unique and I'm almost certain that this is due to data inconsistencies. Here is a list of the duplicates (`page` is the new field encoding recto (f=front) and verso (b=back).

```
Arab.	7	NULL	f
Aram.	1	NULL	b
G.	14	NULL	f
G.	1744	NULL	f
G.	1752	NULL	f
G.	216	NULL	f
G.	22	NULL	f
G.	295	NULL	b
G.	310	NULL	f
G.	32	NULL	f
G.	81	NULL	f
G.	87	NULL	fb
G.	8	NULL	f
Hebr.	1	NULL	b
Hebr.	1	NULL	f
Hebr.	23	NULL	b
Hebr.	23	NULL	f
Hebr.	3	NULL	f
```

I took a quick look at some of these, e.g. *Aram 1* – and to me as a non-expert it looks as if someone made a duplicate entry without checking first, if a previous entry existed. The entries differ very slightly sometimes, but not significantly (again, non-expert look). There might also be cases where `p_heid_inv_buchstabe` might accidentally have been entered into `p_heid_inv_erg` (the reverse of what we corrected in #24).

@jcowey, sorry to bother you again with this, but could you check these please so we can get rid of this issue once and for all?

**Comment by jcowey** [comment]
- [ ] Arab.   7   NULL    f
 - [ ] Aram.   1   NULL    b
 - [ ] G.  14  NULL    f
 - [ ] G.  1744    NULL    f
 - [ ] G.  1752    NULL    f
 - [ ] G.  216 NULL    f
 - [ ] G.  22  NULL    f
 - [ ] G.  295 NULL    b
 - [ ] G.  310 NULL    f
 - [ ] G.  32  NULL    f
 - [ ] G.  81  NULL    f
 - [ ] G.  87  NULL    fb
 - [ ] G.  8   NULL    f
 - [ ] Hebr.   1   NULL    b
 - [ ] Hebr.   1   NULL    f
 - [ ] Hebr.   23  NULL    b
 - [ ] Hebr.   23  NULL    f
 - [ ] Hebr.   3   NULL    f

**Comment by jcowey** [comment]
G. 14: Deleted 11287 and kept 11286.

**Comment by jcowey** [comment]
G. 22: Deleted 11300 and 11302 but kept 11301.

**Comment by jcowey** [comment]
G. 216: Deleted 11553 but kept 11552. Now 15264 records.

**Comment by jcowey** [comment]
G. 295: Deleted 11654 but kept 10942. Now 15263 records.

**Comment by jcowey** [comment]
G. 81: Deleted 11380 but kept 11379. Now 15262 records.

**Comment by jcowey** [comment]
G. 87: Deleted 11390 but kept 11389. Now 15261 records.

**Comment by jcowey** [comment]
G. 1744: Deleted 13415 but kept 13416. Now 15260 records.

**Comment by jcowey** [comment]
G. 1752: Deleted 13428 but kept 13427. Now 15259 records.

**Comment by jcowey** [comment]
G. 8: Deleted 11277 and 11279 but kept 11278. Now 15257 records.

**Comment by jcowey** [comment]
G. 82: Deleted 11315 but kept 11314. Now 15256 records.

**Comment by jcowey** [comment]
G: 310: Deleted 11674-11678 but kept 11673. Now 15251 records.

**Comment by jcowey** [comment]
Hebr. 1: Deleted 4980 and 4981 but kept 19460 and 19468. There is helpful information from W. Diem on the Karteikärtchen zu P.Hebr. 1.

**Comment by jcowey** [comment]
Hebr. 23: Deleted 5006 and 5007 but kept 19484 and 19503. Now 15247.

**Comment by jcowey** [comment]
Hebr. 3: Deleted 4983 but kept 19462. Now 15246 records.

**Comment by jcowey** [comment]
Arab. 7: Deleted 6 but kept 7. Now 15245 records.

**Comment by jcowey** [comment]
Aram. 1: Deleted 8194 but kept 4977 and 4978. Now 15244 records. Info on Negative should be checked.

**Comment by jcowey** [comment]
@kadowa this is now finished!!!!!!!!!!!!!!!!!!!

**Comment by jcowey** [comment]
Done

**Comment by kadowa** [comment]
:tada: :tada: :tada: :dart:
