### ISSUE TITLE
New field papyri_info

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#34]
Should be a list field (several separate transcriptions are possible, if a papyrus page contains more than one text).

**Comment by kadowa** [comment]
Goes into papyrus table.

**Comment by jcowey** [comment]
Content will be (usually only one, but sometimes more than one, so a list field)
papyri.info/ddbdp/p.bad;2;15
papyri.info/ddbdp/p.sarp;;86; papyri.info/ddbdp/p.sarp;;87; papyri.info/ddbdp/p.sarp;;88

Of course the prefix `papyri.info/ddbdp/ could be suppressed.
