### ISSUE TITLE
New field 'ausleihe'

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#36]
@jcowey, this is probably going to be a text field, right? Can you give me a (generous) estimate of how many characters you will need there?

**Comment by kadowa** [comment]
Goes into papyrus table.

**Comment by jcowey** [comment]
Text field yes! Enough space for several entries of the following kind: "20.06.2017 ausgeliehn an Landesmuseum, Karlsruhe; 21.04.2018 ausgeliehen an ÖNB für 4 Wochen."
I hope this helps, I am not very good at estimating character totals for fields.

**Comment by kadowa** [comment]
An example is perfectly fine, thanks!
