### ISSUE TITLE
Different values for 'alte_inventar_nr_*' for the same papyrus

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#37]
@jcowey, this is not urgent, just for documentation.

There are three papyri that have different values for the `alte_inventar_nr_*` fields for the front and back record. In particular:

```
'24469'  'p_arab_7'  NULL    'PSR'   '7'
'24468'  'p_arab_7'  NULL    'PSR'   '5'
'25757'  'p_g_1428'  'b'     NULL    '4300'
'25756'  'p_g_1428'  'a'     '4300'  NULL
'30248'  'p_g_686'   NULL    'P.Graec.'  '64'
'30247'  'p_g_686'   NULL    NULL    '1686'
```

Since the `alte_inventar_nr` fields belongs to the papyrus, one of these values will be lost when we restructure the database. You can use the information in this issue to restore/correct the record later.

**Comment by jcowey** [comment]
@kadowa 
Yes this sort of issue is very helpful as it conserves data. The values can be redistributed when we have the new data model in place. Thanks.
