### ISSUE TITLE
Default page value for unspecified 'rv'

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#38]
There are 746 records in the database that have no information on whether they refer to the front or back of a papyrus (fields `rv` and `andere_seite` are empty). Most are Ostraka, but there are a few papyri as well (listed below). All of their project_ids, with the sole exception of `p_hebr_9`, appear only once, so there is no implicit assignment.

```
SELECT project_id, COUNT(project_id) FROM papyri.papyri WHERE project_id IN (SELECT project_id FROM papyri.papyri WHERE rv IS NULL) GROUP BY project_id;
```

```
# project_id, COUNT(project_id)
p_arab_1002, 1
p_arab_125, 1
p_arab_136, 1
p_arab_138, 1
p_arab_1540, 1
p_arab_181, 1
p_arab_235, 1
p_arab_26, 1
p_arab_326, 1
p_arab_362, 1
p_arab_601, 1
p_arab_61, 1
p_arab_638, 1
p_dem_638, 1
p_dem_639, 1
p_dem_640, 1
p_dem_641, 1
p_dem_642, 1
p_dem_643, 1
p_dem_644, 1
p_g_1631_k, 1
p_g_1702, 1
p_g_1703, 1
p_g_4051, 1
p_g_4867, 1
p_g_4996, 1
p_hebr_12, 1
p_hebr_9, 2
p_hier_2, 1
p_hier_21, 1
p_lat_5, 1
p_pahl_59, 1
p_syr_3, 1
p_syr_4, 1
```

I suggest assigning them per default `rv=r` or `rv=rv` (because we need at least one page per papyrus to store all the information in the restructured database). @jcowey, what do you think?

**Comment by jcowey** [comment]
@kadowa please make a decision that suits you. It can be cleaned up later. Hope all is going well.

**Comment by kadowa** [comment]
No catastrophes so far. :smiley: Keep your fingers crossed!

**Comment by jcowey** [comment]
Great. It is difficult to work in front of a computer with fingers crossed, but I am doing my best ;)
