### ISSUE TITLE
List of papyri with 3 pages

### ISSUE THREAD

**Issue by kadowa** [kadowa/papyri#43]
Copied from #29: List of papyri (identified by DWork project id) with three instead of two pages in the `seiten` table. Pages marked with `fb=f` and `fb=b` are linked; pages originally marked as `fb` are now marked with `fb=NULL`.

```
# project_id, COUNT(project_id)
p_aram_2, 3
p_hebr_10, 3
p_hebr_11, 3
p_hebr_13, 3
p_hebr_14, 3
p_hebr_16, 3
p_hebr_2, 3
p_hebr_21, 3
p_hebr_26, 3
p_hebr_27, 3
p_hebr_28, 3
p_hebr_29, 3
p_hebr_30, 3
p_hebr_31, 3
p_hebr_32, 3
p_hebr_33, 3
p_hebr_4, 3
p_hebr_5, 3
p_hebr_6, 3
p_hebr_7, 3
p_hebr_8, 3
```

**Comment by jcowey** [comment]
@kadowa So the database is now restructured?

**Comment by kadowa** [comment]
Yes! There are now two table links in the web interface menu. Have a look: http://heidi.ub.uni-heidelberg.de/papyri/default/index.html

**Comment by jcowey** [comment]
Congratulations!!
